#!/usr/bin/php
<?php
	

	if($argv[1] == "model"){
		$dir = dirname(dirname(__FILE__))."/app/models/";
		
		if(file_exists($dir.$argv[2].".php")){
			echo('Model '.$argv[2]." already exists... exiting.");
			exit();
		}
		
		echo('Creating model: '.$argv[2]);
		
		$handle = fopen($dir.$argv[2].".php","w");
		$stub  = "<?php \n\n class ".ucwords($argv[2])." extends ActiveRecord{ \n\n";
		$stub .= "\t".'static function find($id, $options = null) { '."\n";
		$stub .= "\t\t".'return parent::find(__CLASS__, $id, $options);'."\n\t}\n\n}";
		
		fwrite($handle,$stub);
		fclose($handle);
		
		echo("....Done.\n");
		
	}
	
	exit();
?>